apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: flask_app:15
          imagePullPolicy: Never
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: MYSQL_HOST
              value: "mysql.default.svc.cluster.local"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "animals"
            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: root_username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: root_password
            - name: MYSQL_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: user_username
            - name: MYSQL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: user_password
          ports:
            - containerPort: 2222
          livenessProbe:
            httpGet:
              path: /health
              port: 2222
            initialDelaySeconds: 8
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 2222
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
