apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 2222
      nodePort: 30003
  type: LoadBalancer
