apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001
  type: NodePort
